<?php
declare(strict_types=1);
require __DIR__ . '/../api/bootstrap.php';
require_admin();
$pdo = db();
$brands = $pdo->query('SELECT id, name, slug FROM brands WHERE is_active = 1 ORDER BY name')->fetchAll();
$brand = trim((string)($_GET['brand'] ?? ''));
$status = trim((string)($_GET['status'] ?? ''));
$where = []; $params = [];
if ($brand !== '') { $where[] = 'b.slug = ?'; $params[] = $brand; }
if ($status !== '') { $where[] = 'l.status = ?'; $params[] = $status; }
$sql = 'SELECT l.*, b.name AS brand_name FROM leads l JOIN brands b ON b.id = l.brand_id' . ($where ? ' WHERE ' . implode(' AND ', $where) : '') . ' ORDER BY l.created_at DESC LIMIT 500';
$statement = $pdo->prepare($sql); $statement->execute($params); $leads = $statement->fetchAll();
$total = (int)$pdo->query('SELECT COUNT(*) FROM leads')->fetchColumn();
$esc = static fn($value): string => htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8');
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Franchise CRM</title><link rel="stylesheet" href="admin.css"></head><body><header class="admin-header"><div><strong>Franchise CRM</strong><span>Welcome, <?= $esc($_SESSION['admin_name']) ?></span></div><a href="logout.php">Sign out</a></header><main class="admin-main"><section class="admin-top"><div><p class="eyebrow">Lead management</p><h1>Franchise leads</h1><p><?= $total ?> total leads</p></div><form class="filters" method="get"><select name="brand"><option value="">All brands</option><?php foreach ($brands as $item): ?><option value="<?= $esc($item['slug']) ?>" <?= $brand === $item['slug'] ? 'selected' : '' ?>><?= $esc($item['name']) ?></option><?php endforeach; ?></select><select name="status"><option value="">All statuses</option><?php foreach (['new','contacted','follow_up','qualified','closed','rejected'] as $item): ?><option value="<?= $item ?>" <?= $status === $item ? 'selected' : '' ?>><?= ucwords(str_replace('_', ' ', $item)) ?></option><?php endforeach; ?></select><button>Filter</button></form></section><section class="lead-table-wrap"><table><thead><tr><th>Lead</th><th>Brand</th><th>Contact</th><th>Location</th><th>Status</th><th>Received</th></tr></thead><tbody><?php foreach ($leads as $lead): ?><tr><td><strong><?= $esc($lead['name']) ?></strong><?php if ($lead['message']): ?><small><?= $esc($lead['message']) ?></small><?php endif; ?></td><td><?= $esc($lead['brand_name']) ?></td><td><a href="tel:+91<?= $esc($lead['mobile']) ?>"><?= $esc($lead['mobile']) ?></a></td><td><?= $esc($lead['city']) ?><small><?= $esc($lead['preferred_location']) ?></small></td><td><form action="update-status.php" method="post"><input type="hidden" name="id" value="<?= (int)$lead['id'] ?>"><input type="hidden" name="return" value="<?= $esc($_SERVER['REQUEST_URI']) ?>"><select name="status" onchange="this.form.submit()"><?php foreach (['new','contacted','follow_up','qualified','closed','rejected'] as $item): ?><option value="<?= $item ?>" <?= $lead['status'] === $item ? 'selected' : '' ?>><?= ucwords(str_replace('_', ' ', $item)) ?></option><?php endforeach; ?></select></form></td><td><?= date('d M Y, g:i A', strtotime($lead['created_at'])) ?></td></tr><?php endforeach; ?><?php if (!$leads): ?><tr><td colspan="6" class="empty">No leads match this filter.</td></tr><?php endif; ?></tbody></table></section></main></body></html>
